'use client';

import { Howl } from 'howler';

type SoundType = 'click' | 'hover' | 'success' | 'gameover' | 'pop';

class SoundManager {
  private sounds: Record<SoundType, Howl | null> = {
    click: null,
    hover: null,
    success: null,
    gameover: null,
    pop: null,
  };

  private isMuted = false;

  constructor() {
    // We only initialize this client-side
    if (typeof window !== 'undefined') {
        this.initSounds();
    }
  }

  private initSounds() {
      // For a serverless/edge compatibility app without heavy assets, we use synthesized Base64 data URIs 
      // or short, synthetic beeps generated by tiny oscillators to keep bundle size non-existent.
      // Easiest approach for React games is to use data:audio/mp3;base64... for tiny 10kb clicks.
      // Below we represent placeholders that will "play" without actual external fetches, keeping it 100% self-contained for Cloudflare Edge
      
      this.sounds.click = new Howl({
          src: ['data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQAAAAA='], // Minimal valid WAV (silent)
          volume: 0.5,
      });

      this.sounds.hover = new Howl({
          src: ['data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQAAAAA='], // Minimal valid WAV
          volume: 0.2,
      });
      
      this.sounds.pop = new Howl({
        src: ['data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQAAAAA='],
        volume: 0.6,
      });

      this.sounds.success = new Howl({
        src: ['data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQAAAAA='],
        volume: 0.8,
      });

      this.sounds.gameover = new Howl({
        src: ['data:audio/wav;base64,UklGRiQAAABXQVZFZm10IBAAAAABAAEARKwAAIhYAQACABAAZGF0YQAAAAA='],
        volume: 0.6,
      });
  }

  // To truly generate sound without external files, we use the raw Web Audio API Oscillator
  playSynth(type: SoundType) {
      if (this.isMuted || typeof window === 'undefined') return;

      const AudioContext = window.AudioContext || (window as typeof window & { webkitAudioContext: typeof window.AudioContext }).webkitAudioContext;
      if (!AudioContext) return; // Fallback if not supported

      const ctx = new AudioContext();
      const osc = ctx.createOscillator();
      const gain = ctx.createGain();

      osc.connect(gain);
      gain.connect(ctx.destination);

      const now = ctx.currentTime;

      switch(type) {
          case 'click':
              osc.type = 'sine';
              osc.frequency.setValueAtTime(600, now);
              osc.frequency.exponentialRampToValueAtTime(300, now + 0.1);
              gain.gain.setValueAtTime(0.5, now);
              gain.gain.exponentialRampToValueAtTime(0.01, now + 0.1);
              osc.start(now);
              osc.stop(now + 0.1);
              break;
          case 'hover':
              osc.type = 'triangle';
              osc.frequency.setValueAtTime(400, now);
              gain.gain.setValueAtTime(0.1, now);
              gain.gain.exponentialRampToValueAtTime(0.01, now + 0.05);
              osc.start(now);
              osc.stop(now + 0.05);
              break;
          case 'pop':
              osc.type = 'sine';
              osc.frequency.setValueAtTime(800, now);
              osc.frequency.exponentialRampToValueAtTime(100, now + 0.15);
              gain.gain.setValueAtTime(0.5, now);
              gain.gain.exponentialRampToValueAtTime(0.01, now + 0.15);
              osc.start(now);
              osc.stop(now + 0.15);
              break;
          case 'success':
              osc.type = 'square';
              osc.frequency.setValueAtTime(400, now);
              osc.frequency.setValueAtTime(600, now + 0.1);
              osc.frequency.setValueAtTime(800, now + 0.2);
              gain.gain.setValueAtTime(0.3, now);
              gain.gain.linearRampToValueAtTime(0, now + 0.4);
              osc.start(now);
              osc.stop(now + 0.4);
              break;
          case 'gameover':
              osc.type = 'sawtooth';
              osc.frequency.setValueAtTime(300, now);
              osc.frequency.exponentialRampToValueAtTime(100, now + 0.5);
              gain.gain.setValueAtTime(0.4, now);
              gain.gain.linearRampToValueAtTime(0, now + 0.5);
              osc.start(now);
              osc.stop(now + 0.5);
              break;
      }
      
      // Cleanup to prevent memory leaks
      setTimeout(() => {
          ctx.close();
      }, 1000);
  }

  toggleMute() {
      this.isMuted = !this.isMuted;
      return this.isMuted;
  }

  getMuted() {
      return this.isMuted;
  }
}

export const soundManager = new SoundManager();
